method: ISCNet
weight_prior: 'out/prior/2022-07-06T18:40:00.208561/weights_epoch_170'
seed: 10
device:
  use_gpu: True
  gpu_ids: '0,1'
  num_workers: 8
data:
  dataset: shapenet
  split: datasets/splits/fullscan
  num_box_points: 2048
  num_query_points: 2048
  shapenet_path: datasets/ShapeNetv2_data_fps2
  hidden_dim: 512
  c_dim: 128
  threshold: 0
  embedding_path: datasets/shape_embeddings.pt
optimizer:
  method: Adam
  lr: 5e-5
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 0
scheduler:
  patience: 20
  factor: 0.1
  threshold: 0.01
bnscheduler:
  bn_decay_step: 20
  bn_decay_rate: 0.5
  bn_momentum_init: 0.5
  bn_momentum_max: 0.001
train:
  epochs: 200
  batch_size: 32
val:
  batch_size: 32
log:
  path: out/prior
generation:
  generate_mesh: True
  resolution_0: 32
  upsampling_steps: 0
  use_sampling: False
  refinement_step: 0
  simplify_nfaces: Null
  dump_threshold: 0.5
  dump_results: True
