method: ISCNet
resume: False
finetune: True
weight: ['out/retrieval/2022-07-07Tskip_propagation_newprior/model_last.pth']
weight_prior: 'out/prior/prior_fps_new/weights_epoch_170'
seed: 10
device:
  use_gpu: True
  gpu_ids: '0'
  num_workers: 0
data:
  dataset: scannet
  split: datasets/splits/fullscan
  num_points: 80000
  num_box_points: 2048
  num_query_points: 2048
  num_target: 256
  vote_factor: 1
  cluster_sampling: seed_fps
  ap_iou_thresh: 0.25
  no_height: False
  use_color_detection: False
  use_color_completion: False
  shapenet_path: datasets/ShapeNetv2_data
  points_unpackbits: True
  points_subsample: [1024, 1024]
  hidden_dim: 512
  c_dim: 128
  threshold: 0
  completion_limit_in_train: 10
  use_cls_for_completion: False
  retrieval: True
  skip_propagate: True
  embedding_path: out/prior/prior_fps_new/shape_embeddings.pt
model:
  backbone:
    method: Pointnet2Backbone
    loss: Null
  voting:
    method: VotingModule
    loss: Null
  detection:
    method: ProposalModule
    loss: DetectionLoss
  skip_propagation:
    method: SkipPropagation
    loss: Null
  group_and_align:
    method: GroupAndAlign
    loss: Null
  shape_prior:
    method: ShapePrior
    loss: Null
test:
  phase: 'completion'
  batch_size: 1
  use_cls_nms: True
  use_3d_nms: True
  ap_iou_thresholds: [0.5]
  faster_eval: False
  nms_iou: 0.25
  use_old_type_nms: False
  per_class_proposal: True
  conf_thresh: 0.05
  evaluate_mesh_mAP: False
generation:
  generate_mesh: True
  resolution_0: 32
  upsampling_steps: 0
  use_sampling: False
  refinement_step: 0
  simplify_nfaces: Null
  dump_threshold: 0.5
  dump_results: True
demo:
  phase: 'completion'
log:
  vis_path: visualization
  save_results: True
  vis_step: 100
  print_step: 10
  path: out/iscnet_test