language: python
python:
- '2.7'
- '3.6'

env:
- USE_OMP=0
- USE_OMP=1 OMP_NUM_THREADS=4

before_install:
- sudo apt-get install python-dev

install:
- python setup.py install

script: python setup.py test 
